config/routes.rb
SampleApp::Application.routes.draw do
  get "feeds/index"
  resources :sessions, only:[:new,:create,:destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'feeds#index'
  match '/signup', to: 'users#new', via: 'get'
  match '/about',   to: 'static_pages#about'  ,via: 'get'
  match '/help',    to: 'static_pages#help'   ,via: 'get'
  match '/contact', to: 'static_pages#contact',via: 'get'
  match '/signin',  to: 'sessions#new'        ,via: 'get'
  match '/signout', to: 'sessions#destroy'    ,via: 'delete'
  match '/news',    to: 'feeds#index'         ,via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> {order('created_at DESC')}
	validates :user_id, presence: true
	validates :content, presence: true #, length: {maximum:140}

 # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user,	only: [:create,:destroy]
	before_action :correct_user,	only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "Micropost create!"
			redirect_to root_url
		else
			@feed_items =[]
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
		redirect_to root_url
	end

	private
		def micropost_params
			params.require(:micropost).permit(:content)
		end
		def correct_user
		      @micropost = current_user.microposts.find_by(id: params[:id])
		      redirect_to root_url if @micropost.nil?
    	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %>ago.
	</span>
	<% if current_user?(micropost.user) %>
	<%= link_to "delete", micropost,method: :delete,
									data: {confirm: "You sure?"},
									title: micropost.content %>
	<% end %>
</li>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>